
ERROR_CODES_WSG = {0: 'SUCCESS', 1: 'E_NOT_AVAILABLE', 2: 'E_NO_SENSOR',
                   3: 'E_NOT_INITIALIZED', 4: 'E_ALREADY_RUNNING', 5: 'E_FEATURE_NOT_SUPPORTED',
                   6: 'E_INCONSISTENT_DATA', 7: 'E_TIMEOUT', 8: 'E_READ_ERROR', 9: 'E_WRITE_ERROR',
                   10: 'E_INSUFFICIENT_RESOURCES', 11: 'E_CHECKSUM_ERROR', 12: 'E_NO_PARAM_EXPECTED',
                   13: 'E_NOT_ENOUGH_PARAMS', 14: 'E_CMD_UNKNOWN', 15: 'E_CMD_FORMAT_ERROR',
                   16: 'E_ACCESS_DENIED', 17: 'E_ALREADY_OPEN', 18: 'E_CMD_FAILED', 19: 'E_CMD_ABORTED',
                   20: 'E_INVALID_HANDLE', 21: 'E_NOT_FOUND', 22: 'E_NOT_OPEN', 23: 'E_IO_ERROR',
                   24: 'E_INVALID_PARAMETER', 25: 'E_INDEX_OUT_OF_BOUNDS', 26: 'E_CMD_PENDING',
                   27: 'E_OVERRUN', 28: 'E_RANGE_ERROR', 29: 'E_AXIS_BLOCKED', 30: 'E_FILE_EXISTS'}

SYSTEM_STATE_FLAGS = ['SF_REFERENCED', 'SF_MOVING', 'SF_BLOCKED_MINUS', 'SF_BLOCKED_PLUS',
                      'SF_SOFT_LIMIT_MINUS', 'SF_SOFT_LIMIT_PLUS', 'SF_AXIS_STOPPED',
                      'SF_TARGET_POS_REACHED', 'SF_OVERRIDE_MODE', 'SF_FORCECNTL_MODE',
                      'RESERVED', 'RESERVED', 'SF_FAST_STOP', 'SF_TEMP_WARNING',
                      'SF_TEMP_FAULT', 'SF_POWER_FAULT', 'SF_CURR_FAULT', 'SF_FINGER_FAULT',
                      'SF_CMD_FAILURE', 'SF_SCRIPT_RUNNING', 'SF_SCRIPT_FAILURE']

print(SYSTEM_STATE_FLAGS[17])